name: SweetInventory
version: '${version}'
main: top.mrxiaom.sweet.inventory.SweetInventory
api-version: 1.13
softdepend:
  - PlaceholderAPI
  - ProtocolLib
  - ItemsAdder
  - MythicLib
  - MMOItems
  - MythicMobs
  - CraftEngine
  - NeigeItems
authors: [ MrXiaoM ]
folia-supported: true
libraries:
  - "${libraries}"
commands:
  sweetinventory:
    description: 'The main command of SweetInventory'
    aliases: [ sinv, si, menu ]
