name: SweetInventory
version: '${version}'
main: top.mrxiaom.sweet.inventory.SweetInventory
api-version: 1.13
depend:
  - Vault
softdepend:
  - ProtocolLib
  - PlaceholderAPI
  - MythicMobs
  - PlayerPoints
authors: [ MrXiaoM ]
commands:
  sweetinventory:
    description: 'The main command of SweetInventory'
    aliases: [ sinv, si ]
