name: SweetInventory
version: '${version}'
main: top.mrxiaom.sweet.inventory.SweetInventory
api-version: 1.13
softdepend:
  - PlaceholderAPI
  - ProtocolLib
  - ItemsAdder
  - MythicLib
  - MMOItems
  - MythicMobs
  - CraftEngine
  - NeigeItems
authors: [ MrXiaoM ]
libraries:
  - "org.jetbrains:annotations:24.0.0"
commands:
  sweetinventory:
    description: 'The main command of SweetInventory'
    aliases: [ sinv, si, menu ]
