name: SweetInventory
version: '${version}'
main: top.mrxiaom.sweet.inventory.SweetInventory
api-version: 1.13
softdepend:
  - PlaceholderAPI
  - ProtocolLib
  - ItemsAdder
  - MythicLib
  - MMOItems
  - MythicMobs
  - CraftEngine
  - NeigeItems
  - SX-Item
authors: [ MrXiaoM ]
folia-supported: true
# PluginBase Libraries ${libraries_config}
commands:
  sweetinventory:
    description: 'The main command of SweetInventory'
    aliases: [ sinv, si, menu ]
